export const hotelReport = {
  ru: {
    hotelRating: 'Оценка отеля',
    overallProgress: 'Общий прогресс',
    progress: 'Прогресс',
    reportFrom: 'Отчет от {date}',
    reportStatus: 'Статус',
    completed: 'Завершен',
    inProgress: 'В процессе',
    totalScore: 'Общая оценка',
    comment: 'Комментарий',
    show: 'Показать',
    addNewReport: 'Добавить новый отчет',
    selectTrip: 'Выберите поездку',
    continue: 'Продолжить',
    reports: 'Отчеты',
    oopsNoMoreRidesAvailable: 'Упс, больше доступных поездок нет',
    reportInformation: 'Информация об отчете',
    guestsOverallReview: 'Суммарный отзыв гостя:',
    user: 'Пользователь',
    published: 'Опубликовано',
    view: 'Просмотреть',
    start: 'Начать',
  },
  en: {
    hotelRating: 'Hotel rating',
    overallProgress: 'Overall progress',
    progress: 'Progress',
    reportFrom: 'Report from {date}',
    reportStatus: 'Status',
    completed: 'Completed',
    inProgress: 'In progress',
    totalScore: 'Total score',
    comment: 'Comment',
    show: 'Show',
    addNewReport: 'Add new report',
    selectTrip: 'Select trip',
    continue: 'Continue',
    reports: 'Reports',
    oopsNoMoreRidesAvailable: 'Oops, no more rides available',
    reportInformation: 'Report Information',
    guestsOverallReview: "Guest's overall review:",
    user: 'User',
    published: 'Published',
    view: 'View',
    start: 'Start',
  },
};
