export const hotelReport = {
  ru: {
    hotelRating: 'Оценка отеля',
    overallProgress: 'Общий прогресс',
    reportFrom: 'Отчет от {date}',
    reportStatus: 'Статус',
    completed: 'Завершен',
    inProgress: 'В процессе',
    totalScore: 'Общая оценка',
    comment: 'Комментарий',
    show: 'Показать',
    addNewReport: 'Добавить новый отчет',
    selectTrip: 'Выберите поездку',
    continue: 'Продолжить',
    reports: 'Отчеты',
    oopsNoMoreRidesAvailable: 'Упс, больше доступных поездок нет',
  },
  en: {
    hotelRating: 'Hotel rating',
    overallProgress: 'Overall progress',
    reportFrom: 'Report from {date}',
    reportStatus: 'Status',
    completed: 'Completed',
    inProgress: 'In progress',
    totalScore: 'Total score',
    comment: 'Comment',
    show: 'Show',
    addNewReport: 'Add new report',
    selectTrip: 'Select trip',
    continue: 'Continue',
    reports: 'Reports',
    oopsNoMoreRidesAvailable: 'Oops, no more rides available',
  },
};
