export const profile = {
  ru: {
    trips: 'Поездки',
    awards: 'Награды',
    yourRewards: 'Ваши награды',
    currentLevel: 'Текущий уровень:',
    progressToTheNextLevel: 'Прогресс до следующего уровня',
    welcome: 'Добро пожаловать,',
    pending: 'Заявка: На рассмотрении',
    approved: 'Заявка: Одобрена',
    rejected: 'Заявка: Отклонена',
    totalTrips: 'Всего поездок',
    completedReports: 'Завершенных отчетов',
    accumulatedPoints: 'Накопленных баллов',
    travelDate: 'Дата поездки:',
    learnMore: 'Подробнее',
    fillOutTheReport: 'Заполнить отчет',
    reportInformation: 'Информация по отчету',
    tripInformation: 'Информация по поездке',
    report: 'Отчет',
    trip: 'Поездка',
    from: 'с',
    to: 'по',
    reportSent: 'Отчет отправлен',
    waitingForReport: 'Ожидает отчета',
    upcomingTrip: 'Предстоящая поездка',
    youDontHaveAnyTripsYet: 'У вас еще нет поездок',
    youDontHaveAnyTripsYetSelectHotel:
      'У вас еще нет поездок. Выберите отель из списка, чтобы создать поездку',
    availableInStatuses: 'Доступно в статусах:',
    notEnoughScore: 'Не хватает баллов',
    youExchangeScore: `Вы обмениваете {score} баллов на награду: {award}`,
    confirmTheExchange: `Подтвердите обмен`,
    cancel: `Отмена`,
    successfulExchange: `Вы успешно обменяли баллы, награда уже зачислена на ваш счет`,
  },
  en: {
    trips: 'Trips',
    awards: 'Awards',
    yourRewards: 'Your rewards',
    currentLevel: 'Current level:',
    progressToTheNextLevel: 'Progress to the next level',
    welcome: 'Welcome',
    pending: 'Application: Under Review',
    approved: 'Application: Approved',
    rejected: 'Application: Rejected',
    totalTrips: 'Total trips',
    completedReports: 'Completed reports',
    accumulatedPoints: 'Accumulated points',
    travelDate: 'Travel date:',
    learnMore: 'Learn more',
    fillOutTheReport: 'Fill out the report',
    reportInformation: 'Report Information',
    tripInformation: 'Trip information',
    report: 'Report',
    trip: 'Trip',
    from: 'from',
    to: 'to',
    reportSent: 'Report sent',
    waitingForReport: 'Waiting for report',
    upcomingTrip: 'Upcoming trip',
    youDontHaveAnyTripsYet: "You don't have any trips yet",
    youDontHaveAnyTripsYetSelectHotel:
      "You don't have any trips yet. Select a hotel from the list to create a trip",
    availableInStatuses: 'Available in statuses:',
    notEnoughScore: 'Not enough score',
    youExchangeScore: `You exchange {score} score for a reward: {award}`,
    confirmTheExchange: `Confirm the exchange`,
    cancel: `Cancel`,
    successfulExchange: `You have successfully redeemed your points and the reward has already been credited to your account.`,
  },
};
